### ISSUE TITLE
Create and upload docs

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever.jl#17]
This requires the credentials of given git user.

Hosting Documentation: https://juliadocs.github.io/Documenter.jl/v0.11.1/man/hosting/

 
Travis runs make.jl. By default it should be able to run and deploy the docs.
**Travis** : https://github.com/weecology/Retriever.jl/blob/master/.travis.yml#L56
**make.jl**: https://github.com/weecology/Retriever.jl/blob/master/docs/make.jl#L23

```
after_success:
  - julia docs/make.jl

```
I am not sure of the commit workflow after a test and deployment.

**Comment by ethanwhite** [comment]
I've tried configuring keys etc and tweaked a couple of the docs related settings in the process. I pushed that commit to trigger and test the build but it looks like we have failing tests now. I rebuilt the last successful build and it's failing as well, so it's something that changed external to the package not this last set of changes.

**Comment by ethanwhite** [comment]
Fixed the tests, but now there are some issues with the docs build. Looking into it.

**Comment by ethanwhite** [comment]
Docs are now building, but not deploying. I've started debugging and have one more try running for the night.

**Comment by ethanwhite** [comment]
![victory-is-mine](https://user-images.githubusercontent.com/744427/38093882-476f511e-333a-11e8-93fd-f26a3750992b.gif)

https://weecology.github.io/Retriever.jl/latest/
