### ISSUE TITLE
pycall api updates

### ISSUE THREAD

**Issue by stevengj** [weecology/retriever.jl#29]
PyCall 1.90.0 is now released, which change `o[:foo]` and `o["foo"]` to `o.foo` and `o."foo"`, respectively, for python objects `o`; see also JuliaPy/PyCall.jl#629.

The old `getindex` methods still work but are deprecated, so you'll want to put out a new release that uses the new methods and REQUIREs PyCall 1.90.0 to avoid having zillions of deprecation messages.

**Comment by henrykironde** [comment]
@stevengj a big thank you from the team at the `Retriever.ji`. This is such a good practice. Is this automated?

**Comment by stevengj** [comment]
No, I just searched the metadata for packages that require PyCall and manually filed issues with packages that seemed active.  It would be nice to have a way to automate this.

**Comment by ethanwhite** [comment]
@henrykironde I did some quick searching of the current `master` branch and couldn't find current usage of either the `[:foo]` notation or `getindex`. If that seems right to you we can close this. If I've missed something (very possible as I'm just digging in) just point me in the right direction and I'll get these updated.

**Comment by henrykironde** [comment]
We do not have this. Thanks for the reminder. I kept this opened to make sure `pycall` works fine before the release. Thanks @stevengj for this update, saved us some time.
