### ISSUE TITLE
No argument for data_dir in csv, xml, json and sqlite engines 

### ISSUE THREAD

**Issue by harshitbansal05** [weecology/retriever.jl#31]
There is no argument for `data_dir` in CSV, JSON, XML, and SQLite engines. The user must be able to pass a `data_dir` argument to install datasets to custom paths.

**Comment by henrykironde** [comment]
Thanks @harshitbansal05, I put in a PR #30

**Comment by ethanwhite** [comment]
Closed by 272a9e137eee993e94b95499beec4cab4b5a79f3.
