### ISSUE TITLE
Should we wrap the CLI or use PyCall?

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever.jl#4]
It's great to see that work is already starting on this project. Very exciting. As it's getting started I think there's one big question to think through, which is whether we want to wrap that CLI as proposed or whether we want to use [PyCall](https://github.com/JuliaPy/PyCall.jl) instead. I don't have any strong feelings on the best way to go, but thought it would be worth taking a quick look at PyCall and making an informed decision before we proceed.

**Comment by ShivamNegi** [comment]
I think using PyCall would be better. I am trying it for the first time, here are my thoughts -
- Julia is currently in a very early stage where there are a lot of changes taking place in the language itself. Using PyCall will make sure that the code doesn't break on the long run. As long as the PyCall package is being update there shouldn't be any problems.
- Changes done in the Python package will directly reflect in the Julia package. This would reduce the development time. 
- There is still one issue I think, how well julia would scale while porting python code. I am trying to figure that out right now.

**Comment by henrykironde** [comment]
I looked at Pycall and  I think it's the way to go
